stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - raw_dataset/apple_quality.csv
    - src/preprocess.py
    - src/utils.py
    outs:
    - processed_dataset/apple_quality.csv
  train:
    cmd: python src/train.py
    deps:
    - processed_dataset/apple_quality.csv
    - src/metrics_and_plots.py
    - src/train.py
    - src/utils.py
    params:
    - random_state
    - train.max_depth
    - train.n_estimators
    outs:
    - metrics/metrics.json
    - models/model.pkl

    plots:
    - metrics/predictions.csv:
        template: confusion
        x: predicted_label
        y: true_label
        x_label: 'Predicted Label'
        y_label: 'True Label'
        title: 'Confusion Matrix'

    - metrics/roc_curve.csv:
        template: simple
        x: fpr
        y: tpr
        x_label: 'False Positive Rate'
        y_label: 'True Positive Rate'
        title: 'ROC Curve'

    - plots/confusion_matrix.png
