name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.gitingore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.gitingore'
  workflow_dispatch:
    inputs:
      PROJECT_NAME:
        description: 'Name of the project'
        required: true
        default: 'cicd-ai'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Printout project name 
        run: echo $PROJECT_NAME >> $GITHUB_ENV

      - name: Setup Python 
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pipx install poetry
          poetry install
        
      - name: Run format
        run: make format

      - name: Run lint
        run:  make lint
      
      - name: Run tests
        run:  make test