name: CI

env:
  AWS_REGION: us-east-1                  # set this to your preferred AWS region, e.g. us-west-1

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'data/**'
      - '.gitingore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'data/**'
      - '.gitingore'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Printout project name 
        run: echo "PROJECT_NAME=$(echo $PROJECT_NAME)" >> $GITHUB_ENV

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pipx install poetry
          poetry install
        
      - name: Run format
        run: make format

      - name: Run lint
        run:  make lint
      
      - name: Run tests
        run:  make test